from app.core.database import SessionLocal
from app.models.organization_models import Organization
from app.models.reference_models import Department, Designation
from app.models.user_models import User
from app.core.security import get_password_hash

def seed_database():
    print("Starting database seeding process...")
    db = SessionLocal()
    
    try:
        # 1. Seed Organization (Idempotent Check)
        org = db.query(Organization).filter(Organization.name == "Healthark").first()
        if not org:
            org = Organization(
                name="Healthark", 
                domain="healthark.com", 
                enabled_features=["dashboard", "goals", "project_reviews"]
            )
            db.add(org)
            db.commit()
            db.refresh(org) # Fetches the new ID generated by the database
            print("Created Organization: Healthark")
        else:
            print("Organization already exists, skipping...")

        # 2. Seed Departments & Designations
        if db.query(Department).count() == 0:
            dept_marketing = Department(org_id=org.id, name="Marketing")
            dept_idt = Department(org_id=org.id, name="IDT")
            dept_strategy = Department(org_id=org.id, name="Strategy")
            
            desig_consultant = Designation(org_id=org.id, name="Consultant", level=1)
            desig_senior_consultant = Designation(org_id=org.id, name="Senior Consultant", level=2)
            desig_manager = Designation(org_id=org.id, name="Manager", level=3)
            desig_senior_manager = Designation(org_id=org.id, name="Senior Manager", level=4)
            desig_associate_director = Designation(org_id=org.id, name="Associate Director", level=5)
            desig_director = Designation(org_id=org.id, name="Director", level=6)
            desig_senior_data_analyst = Designation(org_id=org.id, name="Senior Data Analyst", level=7)
            desig_data_analyst = Designation(org_id=org.id, name="Data Analyst", level=8)
            desig_junior_data_analyst = Designation(org_id=org.id, name="Junior Data Analyst", level=9)
            
            # db.add_all allows us to insert an array of objects efficiently
            db.add_all([dept_marketing, dept_idt, dept_strategy, desig_consultant, desig_senior_consultant, desig_manager, desig_senior_manager, desig_associate_director, desig_director, desig_senior_data_analyst, desig_data_analyst, desig_junior_data_analyst])
            db.commit()
            print("Created Departments & Designations")
        else:
            print("Reference data already exists, skipping...")

        # 3. Seed Users (The Hierarchy)
        if db.query(User).count() == 0:
            # Re-fetch the IDs we just created
            dept_marketing = db.query(Department).filter_by(name="Marketing").first()
            desig_director = db.query(Designation).filter_by(name="Director").first()
            desig_junior_data_analyst = db.query(Designation).filter_by(name="Junior Data Analyst").first()

            # Create the Mentor First
            mentor = User(
                org_id=org.id,
                department_id=dept_marketing.id,
                designation_id=desig_director.id,
                employee_code="EMP-001",
                full_name="David Miller",
                email="david@healthark.com",
                role="Manager",
                password_hash=get_password_hash("password123") # Secure hashing
            )
            db.add(mentor)
            db.commit()
            db.refresh(mentor)

            # Create the Mentee and link to the Mentor
            mentee = User(
                org_id=org.id,
                department_id=dept_marketing.id,
                designation_id=desig_junior_data_analyst.id,
                employee_code="EMP-002",
                full_name="Rahul",
                email="rahul@healthark.com",
                role="Staff",
                mentor_id=mentor.id, # Hierarchical Link!
                password_hash=get_password_hash("password123")
            )
            db.add(mentee)
            db.commit()
            print("Created Users: David (Mentor) and Rahul (Mentee)")
        else:
            print("Users already exist, skipping...")

        print("Database seeding completed successfully!")

    except Exception as e:
        # If ANYTHING goes wrong, we rollback the entire transaction
        print(f"Error seeding database: {e}")
        db.rollback()
    finally:
        # We ALWAYS close the connection to prevent memory leaks
        db.close()

if __name__ == "__main__":
    seed_database()