import { Save, Info } from "lucide-react";
import type { CycleType } from "../../services/system-settings.service";

interface SystemSettingsTabProps {
  readonly activeCycleName: string; // The dynamically computed string from the backend
  readonly cycleType: CycleType;
  readonly onCycleTypeChange: (val: CycleType) => void;
  readonly fiscalStartMonth: number;
  readonly onFiscalStartMonthChange: (val: number) => void;
  readonly onSave: () => void;
  readonly isSaving: boolean;
  readonly settingsSaved: boolean;
}

const MONTHS = [
  { value: 1, label: "January" },
  { value: 2, label: "February" },
  { value: 3, label: "March" },
  { value: 4, label: "April" },
  { value: 5, label: "May" },
  { value: 6, label: "June" },
  { value: 7, label: "July" },
  { value: 8, label: "August" },
  { value: 9, label: "September" },
  { value: 10, label: "October" },
  { value: 11, label: "November" },
  { value: 12, label: "December" },
];

export function SystemSettingsTab({
  activeCycleName,
  cycleType,
  onCycleTypeChange,
  fiscalStartMonth,
  onFiscalStartMonthChange,
  onSave,
  isSaving,
  settingsSaved,
}: SystemSettingsTabProps) {
  return (
    <div className="p-6 max-w-2xl">
      <h3 className="font-display text-lg font-semibold text-text-main mb-4">
        Performance Cycle Configuration
      </h3>

      <div className="space-y-6 bg-surface p-5 rounded-xl border border-border shadow-sm">
        
        {/* Calculated Active Cycle (Read-Only) */}
        <div>
          <label className="block text-sm font-medium text-text-main mb-1">
            Current Active Cycle
          </label>
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={activeCycleName || "System Calculated..."}
              disabled
              className="w-full sm:w-64 rounded-lg border border-border bg-gray-50 px-3 py-2 text-sm text-text-muted cursor-not-allowed"
            />
            <span className="flex items-center gap-1.5 text-xs text-text-muted bg-gray-100 px-2 py-1 rounded-md border border-gray-200">
              <Info className="w-3.5 h-3.5" />
              System Calculated
            </span>
          </div>
          <p className="mt-1.5 text-xs text-text-muted">
            The active cycle is dynamically generated by the system based on the current date, your selected cadence, and fiscal start month.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* Cadence Dropdown */}
          <div>
            <label htmlFor="cycle-type" className="block text-sm font-medium text-text-main mb-1">
              Cycle Cadence
            </label>
            <select
              id="cycle-type"
              value={cycleType}
              onChange={(e) => onCycleTypeChange(e.target.value as CycleType)}
              className="w-full rounded-lg border border-border bg-white px-3 py-2 text-sm text-text-main focus:outline-none focus:ring-2 focus:ring-brand"
            >
              <option value="quarterly">Quarterly</option>
              <option value="half_yearly">Half-Yearly</option>
              <option value="annual">Annual</option>
            </select>
          </div>

          {/* Fiscal Start Month Dropdown */}
          <div>
            <label htmlFor="fiscal-start" className="block text-sm font-medium text-text-main mb-1">
              Fiscal Start Month
            </label>
            <select
              id="fiscal-start"
              value={fiscalStartMonth}
              onChange={(e) => onFiscalStartMonthChange(Number(e.target.value))}
              className="w-full rounded-lg border border-border bg-white px-3 py-2 text-sm text-text-main focus:outline-none focus:ring-2 focus:ring-brand"
            >
              {MONTHS.map((m) => (
                <option key={m.value} value={m.value}>
                  {m.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Save Actions */}
        <div className="pt-4 flex items-center justify-between border-t border-border mt-2">
          {settingsSaved ? (
            <p className="text-sm text-green-600 font-medium animate-[fadeIn_0.3s_ease-in-out]">
              ✓ Configuration saved successfully.
            </p>
          ) : <div />}

          <button
            type="button"
            onClick={onSave}
            disabled={isSaving}
            className="flex items-center gap-2 rounded-lg bg-brand px-5 py-2 text-sm font-medium text-white hover:bg-brand/90 disabled:opacity-70 disabled:cursor-not-allowed transition-all shadow-sm"
          >
            <Save className="h-4 w-4" aria-hidden="true" />
            {isSaving ? "Saving…" : "Save Configuration"}
          </button>
        </div>
      </div>
    </div>
  );
}