"""add_approval_status_to_goals

Revision ID: 37e79adeead9
Revises: 3e62cf7af54a
Create Date: 2026-04-09 18:27:42.295272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e79adeead9'
down_revision: Union[str, None] = '3e62cf7af54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('goals', sa.Column(
        'approval_status',
        sa.String(),
        nullable=False,
        server_default='draft'   # ← fills existing rows, satisfies NOT NULL
    ))
    op.add_column('goals', sa.Column(
        'manager_feedback',
        sa.Text(),
        nullable=True            # ← nullable, no default needed
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'manager_feedback')
    op.drop_column('goals', 'approval_status')
    # ### end Alembic commands ###
