"""create_system_settings_table

Revision ID: 3e62cf7af54a
Revises: a5dc3f65a4a2
Create Date: 2026-04-09 16:50:02.344106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e62cf7af54a'
down_revision: Union[str, None] = 'a5dc3f65a4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
