"""create_goal_criteria_table

Revision ID: 5c09c94243f1
Revises: 1931ea7df013
Create Date: 2026-04-13 10:39:07.740070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c09c94243f1'
down_revision: Union[str, None] = '1931ea7df013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_comments', sa.Text(), nullable=True),
    sa.Column('proof_attachment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_criteria_goal_org', 'goal_criteria', ['goal_id', 'org_id'], unique=False)
    op.create_index(op.f('ix_goal_criteria_id'), 'goal_criteria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_criteria_id'), table_name='goal_criteria')
    op.drop_index('ix_goal_criteria_goal_org', table_name='goal_criteria')
    op.drop_table('goal_criteria')
    # ### end Alembic commands ###
