"""create_project_and_review_tables

Revision ID: 73b1647e09c3
Revises: c222a428eab6
Create Date: 2026-04-14 00:44:08.159072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b1647e09c3'
down_revision: Union[str, None] = 'c222a428eab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('allocated_hours', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index('ix_projects_org_code', 'projects', ['org_id', 'project_code'], unique=True)
    op.create_table('project_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.String(), nullable=True),
    sa.Column('evaluator_type', sa.String(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assignments_id'), 'project_assignments', ['id'], unique=False)
    op.create_index('ix_project_assignments_org_proj_user', 'project_assignments', ['org_id', 'project_id', 'user_id'], unique=True)
    op.create_table('project_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('self_desc_task_execution', sa.Text(), nullable=True),
    sa.Column('self_desc_ownership', sa.Text(), nullable=True),
    sa.Column('self_desc_project_management', sa.Text(), nullable=True),
    sa.Column('self_desc_client_deliverables', sa.Text(), nullable=True),
    sa.Column('self_desc_communication', sa.Text(), nullable=True),
    sa.Column('self_desc_mentoring', sa.Text(), nullable=True),
    sa.Column('self_desc_firm_growth', sa.Text(), nullable=True),
    sa.Column('self_desc_competency_skills', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_reviews_id'), 'project_reviews', ['id'], unique=False)
    op.create_index('ix_project_reviews_org_user_proj_cycle', 'project_reviews', ['org_id', 'user_id', 'project_id', 'cycle'], unique=True)
    op.create_table('project_review_evaluators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_review_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('performance_group', sa.String(), nullable=True),
    sa.Column('impact_statement', sa.Text(), nullable=True),
    sa.Column('comment_task_execution', sa.Text(), nullable=True),
    sa.Column('comment_ownership', sa.Text(), nullable=True),
    sa.Column('comment_project_management', sa.Text(), nullable=True),
    sa.Column('comment_client_deliverables', sa.Text(), nullable=True),
    sa.Column('comment_communication', sa.Text(), nullable=True),
    sa.Column('comment_mentoring', sa.Text(), nullable=True),
    sa.Column('comment_firm_growth', sa.Text(), nullable=True),
    sa.Column('comment_competency_skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_review_id'], ['project_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_evaluators_review_evaluator', 'project_review_evaluators', ['project_review_id', 'evaluator_id'], unique=True)
    op.create_index(op.f('ix_project_review_evaluators_id'), 'project_review_evaluators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_review_evaluators_id'), table_name='project_review_evaluators')
    op.drop_index('ix_pr_evaluators_review_evaluator', table_name='project_review_evaluators')
    op.drop_table('project_review_evaluators')
    op.drop_index('ix_project_reviews_org_user_proj_cycle', table_name='project_reviews')
    op.drop_index(op.f('ix_project_reviews_id'), table_name='project_reviews')
    op.drop_table('project_reviews')
    op.drop_index('ix_project_assignments_org_proj_user', table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    op.drop_index('ix_projects_org_code', table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
