"""create_annual_reviews_table

Revision ID: c222a428eab6
Revises: 5c09c94243f1
Create Date: 2026-04-13 11:30:08.480070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c222a428eab6'
down_revision: Union[str, None] = '5c09c94243f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('cycle_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('self_desc_ownership', sa.Text(), nullable=True),
    sa.Column('self_desc_productivity', sa.Text(), nullable=True),
    sa.Column('self_desc_communication', sa.Text(), nullable=True),
    sa.Column('self_desc_leadership', sa.Text(), nullable=True),
    sa.Column('self_desc_adaptability', sa.Text(), nullable=True),
    sa.Column('self_desc_time_management', sa.Text(), nullable=True),
    sa.Column('self_stars', sa.Integer(), nullable=True),
    sa.Column('mentor_comment_ownership', sa.Text(), nullable=True),
    sa.Column('mentor_comment_productivity', sa.Text(), nullable=True),
    sa.Column('mentor_comment_communication', sa.Text(), nullable=True),
    sa.Column('mentor_comment_leadership', sa.Text(), nullable=True),
    sa.Column('mentor_comment_adaptability', sa.Text(), nullable=True),
    sa.Column('mentor_comment_time_management', sa.Text(), nullable=True),
    sa.Column('mentor_stars', sa.Integer(), nullable=True),
    sa.Column('management_stars', sa.Integer(), nullable=True),
    sa.Column('final_stars', sa.Integer(), nullable=True),
    sa.Column('management_comments', sa.Text(), nullable=True),
    sa.Column('final_rating_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_reviews_id'), 'annual_reviews', ['id'], unique=False)
    op.create_index('ix_annual_reviews_org_user_cycle', 'annual_reviews', ['org_id', 'user_id', 'cycle_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annual_reviews_org_user_cycle', table_name='annual_reviews')
    op.drop_index(op.f('ix_annual_reviews_id'), table_name='annual_reviews')
    op.drop_table('annual_reviews')
    # ### end Alembic commands ###
