"""add_approval_status_to_goals

Revision ID: e0edd4990bcc
Revises: e5111f123d95
Create Date: 2026-04-09 18:47:26.776924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0edd4990bcc'
down_revision: Union[str, None] = 'e5111f123d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('progress_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'progress_notes')
    # ### end Alembic commands ###
